 
build
test

job_build:
  stage: build
  script:
    - cd backend    
    - cd VehicleRental
    - .\gradlew assemble --no-daemon

job_test:
  stage: test
  script:
    - cd backend 
    - cd VehicleRental
    - .\gradlew test --no-daemon