package com.swiftly.domain.enums.vehicle;

public enum Feature {
    AIR_CONDITIONING,
    ELECTRIC_WINDOWS,
    HEATED_SEATS,
    ELECTRIC_MIRRORS,
    ALL_WHEEL_DRIVE,
    REAR_WHEEL_DRIVE,
    FRONT_WHEEL_DRIVE,
    HEAD_UP_DISPLAY,
    NAVIGATION,
    VENTILATED_SEATS,
    BLUETOOTH,
    APPLE_CAR_PLAY,
    ANDROID_AUTO,
    KEYLESS_START,
    SUNROOF,
    CRUISE_CONTROL,
    LANE_ASSIST,
    DISTANCE_ASSIST
}
