CREATE TABLE IF NOT EXISTS public.users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(150) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON public.users(email);

CREATE TABLE IF NOT EXISTS public.profiles (
    id            INTEGER PRIMARY KEY,
    city          VARCHAR(100),
    country       VARCHAR(100),
    address       VARCHAR(100),
    avatar_url    VARCHAR(255),
    full_name     VARCHAR(100),
    locale        VARCHAR(255),
    phone         VARCHAR(17),
    postal_code   VARCHAR(100),
    timezone      VARCHAR(255)
    );
ALTER TABLE public.profiles
    ADD CONSTRAINT fk_profiles_users
        FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS public.vehicles (
                                               id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               vin               VARCHAR(17),
    color             VARCHAR(100),
    features          SMALLINT[],
    fuel_consumption  DOUBLE PRECISION,
    fuel_type         SMALLINT,
    make              VARCHAR(100),
    model             VARCHAR(100),
    owner_id          INTEGER,
    renter_id         INTEGER,
    type              SMALLINT,
    year              INTEGER
    );

ALTER TABLE public.vehicles
    ADD CONSTRAINT fk_vehicles_owner_profile
        FOREIGN KEY (owner_id) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.vehicles
    ADD CONSTRAINT fk_vehicles_renter_profile
        FOREIGN KEY (renter_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_vehicles_owner ON public.vehicles(owner_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_renter ON public.vehicles(renter_id);

CREATE TABLE IF NOT EXISTS public.listings (
                                               id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               base_price_per_day   NUMERIC(10,2) NOT NULL,
    creation_date        TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    description          VARCHAR(1000),
    end_availability     TIMESTAMPTZ(6) NOT NULL,
    instant_book         BOOLEAN NOT NULL,
    latitude             DOUBLE PRECISION,
    longitude            DOUBLE PRECISION,
    pick_up_address      VARCHAR(255),
    start_availability   TIMESTAMPTZ(6) NOT NULL,
    time_zone            VARCHAR(64),
    title                VARCHAR(100) NOT NULL,
    vehicle_id           INTEGER NOT NULL
    );
ALTER TABLE public.listings
    ADD CONSTRAINT fk_listings_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_listings_vehicle ON public.listings(vehicle_id);

CREATE TABLE IF NOT EXISTS public.blackouts (
                                                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                creation_date  TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    end_at         TIMESTAMPTZ(6) NOT NULL,
    start_at       TIMESTAMPTZ(6) NOT NULL,
    vehicle_id     INTEGER NOT NULL
    );
ALTER TABLE public.blackouts
    ADD CONSTRAINT fk_blackouts_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_blackouts_vehicle ON public.blackouts(vehicle_id);

CREATE TABLE IF NOT EXISTS public.bookings (
                                               id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               creation_date  TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    end_at         TIMESTAMPTZ(6) NOT NULL,
    start_at       TIMESTAMPTZ(6) NOT NULL,
    status         VARCHAR(16) NOT NULL,
    total_price    NUMERIC(12,2) NOT NULL,
    profile_id     INTEGER NOT NULL,
    vehicle_id     INTEGER NOT NULL
    );
ALTER TABLE public.bookings
    ADD CONSTRAINT fk_bookings_profile
        FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.bookings
    ADD CONSTRAINT fk_bookings_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_bookings_profile ON public.bookings(profile_id);
CREATE INDEX IF NOT EXISTS idx_bookings_vehicle ON public.bookings(vehicle_id);

-- Auth: refresh tokens
CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(255) UNIQUE NOT NULL,
    expiry_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id         INTEGER NOT NULL,
    revoked         BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE CASCADE
);