ALTER TABLE IF EXISTS public.listings
    ADD COLUMN IF NOT EXISTS isRemoved BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS public.vehicles
    ADD COLUMN IF NOT EXISTS isRemoved BOOLEAN NOT NULL DEFAULT FALSE;