ALTER TABLE IF EXISTS public.listings
    DROP COLUMN IF EXISTS isRemoved;

ALTER TABLE IF EXISTS public.listings
    ADD COLUMN IF NOT EXISTS is_removed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS public.vehicles
    DROP COLUMN IF EXISTS isRemoved;

ALTER TABLE IF EXISTS public.vehicles
    ADD COLUMN IF NOT EXISTS is_removed BOOLEAN NOT NULL DEFAULT FALSE;