-- Drop and recreate refresh_tokens table with correct schema
DROP TABLE IF EXISTS public.refresh_tokens;

CREATE TABLE IF NOT EXISTS public.refresh_tokens(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(255) UNIQUE NOT NULL,
    expiry_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id INTEGER  NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);
