spring.application.name=persistence

spring.datasource.url=jdbc:postgresql://localhost:5431/swiftly
spring.datasource.username=549842
spring.datasource.password=Joh57687
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
