server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/swiftly
    username: "549842"
    password: Joh57687
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
          hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  doc:
    default-produces-media-type: application/json

