server:
  port: 8080

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173

spring:
  flyway:
    enabled: true
    locations: classpath:db-persistence.migrations
    baseline-on-migrate: false
    baseline-version: 1
    validate-on-migrate: true
    clean-disabled: true
  config:
    import:
      - "classpath:application-persistence.properties"
      - "classpath:jwt.properties"
      - "optional:file:boot/.env[.properties]"

  doc:
    default-produces-media-type: application/json
